export const virtualData = [
    {
    stt: '1',
    ngay: '2025-08-01',
    gio: '08:00',
    tram: 'Trạm A',
    truBom: 'Trụ 1',
    matHang: 'DO',
    soLuong: 150,
    donGia: 23500,
    thanhTien: 3525000,
    trangThaiThanhToan: 'Đã thanh toán',
    maKhachHang: 'KH001',
    tenKhachHang: 'Nguyễn Văn A',
    loaiKhachHang: 'Cá nhân',
    ngayThanhToan: '2025-08-02',
    nhanVien: 'Nguyễn Thị B',
    bienSoXe: '29A-123.45',
    trangThaiHoaDon: 'Đã xuất',
  },
  {
    stt: '2',
    ngay: '2025-08-01',
    gio: '09:15',
    tram: 'Trạm B',
    truBom: 'Trụ 2',
    matHang: 'Xăng RON95',
    soLuong: 90,
    donGia: 24500,
    thanhTien: 2205000,
    trangThaiThanhToan: 'Chưa thanh toán',
    maKhachHang: 'KH002',
    tenKhachHang: 'Lê Văn C',
    loaiKhachHang: 'Doanh nghiệp',
    ngayThanhToan: '',
    nhanVien: 'Phạm Văn D',
    bienSoXe: '30F-678.90',
    trangThaiHoaDon: 'Chưa xuất',
  },
  {
    stt: '3',
    ngay: '2025-08-02',
    gio: '10:00',
    tram: 'Trạm A',
    truBom: 'Trụ 3',
    matHang: 'DO',
    soLuong: 200,
    donGia: 23000,
    thanhTien: 4600000,
    trangThaiThanhToan: 'Đã thanh toán',
    maKhachHang: 'KH003',
    tenKhachHang: 'Trần Thị E',
    loaiKhachHang: 'Cá nhân',
    ngayThanhToan: '2025-08-03',
    nhanVien: 'Ngô Văn F',
    bienSoXe: '31A-987.65',
    trangThaiHoaDon: 'Đã xuất',
  },
]